create table if not exists security_events (
    id bigint generated by default as identity primary key,
    device_id text not null,
    event_type text not null,
    source_ip text not null,
    failed_attempts integer default 0,
    message text,
    threat text,
    risk_score integer,
    severity text,
    confidence integer,
    explanation text,
    recommendation text,
    latitude double precision,
    longitude double precision,
    created_at timestamptz default now()
);

create index if not exists idx_security_events_created_at
on security_events(created_at desc);

create index if not exists idx_security_events_severity
on security_events(severity);
